spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testDB?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Wkddnjswhd55%

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql
#  servlet:
#    multipart:
#      enabled: true
#      location:
#      max-file-size: 20MB
#      max-request-size: 20MB
#      file-size-threshold: 1MB

security:
  jwt:
    token:
      security-key:secret-key
      expiration-length:3600000

server:
  port: 8080

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG